### ISSUE TITLE
Fails with latest ClojureScript version

### ISSUE THREAD

**Issue by juliangamble** [asakeron/cljs-webgl#10]
When you change the ClojureScript version in the `project.clj`
````
:dependencies [[org.clojure/clojurescript "0.0-3211"]]
````
and then run the REPL:
````
lein trampoline cljsbuild repl-listen
````
This blows up with the error
````
clojure.lang.ExceptionInfo:  {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4327)
	at cljs.analyzer$error.invoke(analyzer.clj:380)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1944)
	at cljs.analyzer$parse_ns$fn__2142$fn__2143.invoke(analyzer.clj:2074)
	at cljs.analyzer$parse_ns$fn__2142.invoke(analyzer.clj:2074)
	at cljs.analyzer$parse_ns.invoke(analyzer.clj:2055)
	at cljs.analyzer$parse_ns.invoke(analyzer.clj:2046)
	at cljs.analyzer$analyze_file.invoke(analyzer.clj:2170)
	at cljs.compiler$with_core_cljs.invoke(compiler.clj:963)
	at cljs.repl$repl_STAR_.invoke(repl.clj:775)
	at cljs.repl$repl.doInvoke(repl.clj:925)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at cljsbuild.repl.listen$run_repl_listen.invoke(listen.clj:10)
	at user$eval4707.invoke(form-init695590658295671460.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at cljs.core$import_macros$fn__4728.invoke(core.clj:54)
	at clojure.core$map$fn__4207.invoke(core.clj:2485)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$map$fn__4211.invoke(core.clj:2490)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:67)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$concat$cat__3925$fn__3926.invoke(core.clj:687)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
	at clojure.lang.Compiler.eval(Compiler.java:6606)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5018.invoke(core.clj:5530)
	at clojure.core$load.doInvoke(core.clj:5529)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cljs.analyzer$load_core.invoke(analyzer.clj:320)
	at cljs.analyzer$analyze$fn__2114.invoke(analyzer.clj:1950)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1946)
	... 25 more
````

**Comment by asakeron** [comment]
I pushed a possible fix in commit 10fc1280eac5110550a588252198e54259441a3c. Would you mind trying it before I merge it into master?
